### ISSUE TITLE
[Question] How to use CNN with Goroutines (parallelism)

### ISSUE THREAD

**Issue by gg187on** [LdDl/cnns#19]
Hello,

How can I use CNN with Goroutines (parallelism)? Can it be used like that?

Thanks for answer.

**Comment by LdDl** [comment]
Hello @gg187on 
Goroutines are not used in current implementation.
I guess it could boost perfomance significantly: e.g. for [Convolve2D](https://github.com/LdDl/cnns/blob/master/convolve_2d.go#L15) and similar.

If you have some ideas how to do it right way (without loosing actual perfomance and keep simplicity), you can make PR
